# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7.0

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: yarn global add caprover
      - run: caprover deploy -h https://captain.caprover.vormadal.com -b $CIRCLE_BRANCH -c ./captain-definition-frontend --appToken $APP_TOKEN  -a vormadal-docs

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - circleci-project-setup
