# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    executor: node/default
    parameters:
      app:
        type: string
      token:
        type: string
    steps:
      - checkout
      - run: yarn add caprover
      - run: >
          node_modules/.bin/caprover deploy -h https://captain.caprover.vormadal.com 
          -b $CIRCLE_BRANCH 
          -c ./captain-definition 
          --appToken << parameters.token >> 
          -a "<< parameters.app >>"
  verify:
    executor: node/default
    parameters:
      app:
        type: string
    steps:
      - checkout
      - run: yarn add caprover
      - run: node ./scripts/waitForDeploymentCompletion.js appName=<< parameters.app >> password=${CAPTAIN_PASSWORD} cwd=/home/circleci/project/node_modules/.bin
  test:
    # executor: node/default
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: | 
          cd frontend
          yarn
          yarn run cypress:run
      - store_artifacts:
          path: /home/circleci/project/frontend/cypress/videos
      - store_artifacts:
          path: /home/circleci/project/frontend/cypress/screenshots

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - deploy:
          name: deploy-test
          token: $TEST_APP_TOKEN
          app: test-vormadal-docs
          filters:
            branches:
              only:
                - cypress
      - verify:
          name: verify-test
          app: test-vormadal-docs
          requires:
            - deploy-test
      # - test
      - cypress/run:
          name: run integration tests
          executor: cypress/base-14
          install-command: yarn install --ignore-engines
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}
          store_artifacts: true
          working_directory: frontend
          yarn: true
          env: 'CY_BASE_URL=${CY_BASE_URL},CY_TEST_USER_EMAIL=${CY_TEST_USER_EMAIL},CY_TEST_USER_PASSWORD=${CY_TEST_USER_PASSWORD}'
          # requires:
          #   - verify-test
      # - deploy:
      #     name: deploy-production
      #     token: $APP_TOKEN
      #     app: vormadal-docs
      #     requires:
      #       - "run integration tests"
      # - verify:
      #     name: verify-production
      #     app: vormadal-docs
      #     requires:
      #       - deploy-production
