name: Vormadal Docs CI

on:
  push:
    branches:
      - "actions"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          yarn add caprover
          node ./scripts/waitForDeploymentCompletion.js appName=test-vormada-docs password=${{ secrets.CAPROVER_PASSWORD }} cwd=node_modules/.bin
